# H1 TITLE
## H2 TITLE

In [1]:
print("Buy the dip ?")

Buy the dip ?


# Exercise 1
## Numpy array (data types)

In [1]:
import numpy as np

my_array = np.array([
    10, #int
    3.142, #float
    "hello world", #string
    {"key":"value"}, #dictionary
    [1,2,3], #list
    (2,4,6), #tuple
    {4,8,12}, #set
    True, #boolean
    
], dtype=object) #the dtype=object is used to store heterogeneous types

for i in my_array:
    print(type(i))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'dict'>
<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'bool'>


#Exercise 2
## numpy arrays with zeros

In [4]:
import numpy as np

#this creates a 1D array of dimention 300 with zeros(1,300)
zero_array = np.zeros(300)
# print(zero_array)

#reshape it to (3,100)
reshaped_array = zero_array.reshape(3,100)
print(reshaped_array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]]


# Exercise 3: Slicing
## The goal of this exercise is to learn NumPy indexing/slicing. It allows to access values of the NumPy array efficiently and without a for loop.

In [9]:
import numpy as np

#an array of 100 int
arr_1_to_100 = np.arange(1,101)
# print(arr_1_to_100)

 #array for odd intergers
odd_array = arr_1_to_100[::2] #or arr_1_to_100[arr_1_to_100 % 2 == 1]
# print(odd_array)

#array with even interger reversed
even_array = arr_1_to_100[1::2][::-1]
# print(even_array)

#array with each third element from 2nd set to 0
modified_array = arr_1_to_100.copy() #not to change the original
modified_array[1::3] = 0
print(modified_array)


[  1   0   3   4   0   6   7   0   9  10   0  12  13   0  15  16   0  18
  19   0  21  22   0  24  25   0  27  28   0  30  31   0  33  34   0  36
  37   0  39  40   0  42  43   0  45  46   0  48  49   0  51  52   0  54
  55   0  57  58   0  60  61   0  63  64   0  66  67   0  69  70   0  72
  73   0  75  76   0  78  79   0  81  82   0  84  85   0  87  88   0  90
  91   0  93  94   0  96  97   0  99 100]


# Exercise 4: Random generator
## Generating random data with normal and uniform distributions

In [28]:
import numpy as np

np.random.seed(888) #makes the random numbers reproducible

normal_1d = np.random.randn(100)

# print(f"shape: {normal_1d.shape}")
# print(f"sample: {normal_1d[:4]}...\n")

#8x8 uniform integer array (1-10) aka 2d
uniform_2d = np.random.randint(1,11,size=(8,8))
# print(f" shape: {uniform_2d.shape}\n")
# print(uniform_2d)

#4x2x5 uniform integer array (1-17)

uniform_3d = np.random.randint(1,18,size=(4,2,5))
print(f"shape: {uniform_3d.shape}")
print(uniform_3d)

shape: (4, 2, 5)
[[[ 5  2 13 16 15]
  [ 5  5  2 11  3]]

 [[ 8 13  6  4 17]
  [ 2  8  1 13 10]]

 [[12 17 17 12  1]
  [10  8 17  5 11]]

 [[ 9 14  2 15 13]
  [12 14  6 14  2]]]


# Exercise 5: Split, concatenate, reshape arrays
## kuiva array manipulations

In [41]:
import numpy as np

array_1=np.arange(1,51)
print(f"{array_1}\n")

array_2= np.arange(51,101)
print(f"{array_2}\n")

#concate
concate = np.concatenate([array_1,array_2])
print(f"{concate}\n")

#reshape matrix (10,10)
reshaped = concate.reshape(10,10)
print(reshaped)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]

[ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100]

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54

# Exercise 6: Broadcasting and Slicing
## The goal of this exercise is to learn to access values of n-dimensional arrays efficiently.

In [53]:
import numpy as np

#creating a 9x9 ones array
base_arr = np.ones((9,9),dtype=np.int8)
print(base_arr,"\n")

# creating the inner patterns using slices
pattern = base_arr.copy()
pattern[1:8,1:8]=0
pattern[2:7,2:7]=1
pattern[3:6,3:6]=0
pattern[4,4]=1

print(pattern,"\n")

#broadcasting
array_1 = np.array([1,2,3,4,5], dtype=np.int8)
array_2 = np.array([1,2,3], dtype=np.int8)
result= array_1.reshape(-1,1)*array_2
print(result)


[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]] 

[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]] 

[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]]


# Exercise 7: NaN
## Handling missing data in numpy arrays

In [57]:
import numpy as np

generator = np.random.default_rng(123)
grades = np.round(generator.uniform(low=0.0,high=10.0,size=(10,2)))
grades[[1,2,5,7],[0,0,0,0]] = np.nan
# print(grades)

#third_column, uses first column if available
third_col = np.where(np.isnan(grades[:,0]),grades[:,1],grades[:,0])
final_grade = np.hstack([grades,third_col.reshape(-1,1)])
print(final_grade)

[[ 7.  1.  7.]
 [nan  2.  2.]
 [nan  8.  8.]
 [ 9.  3.  9.]
 [ 8.  9.  8.]
 [nan  2.  2.]
 [ 8.  2.  8.]
 [nan  6.  6.]
 [ 9.  2.  9.]
 [ 8.  5.  8.]]


# Exercise 8: Wine Dataset Analysis
## Fundamental data analysis using NumPy

In [60]:
import numpy as np
import urllib.request
import os
import tempfile


# Step 1: Load the data from the provided URL
url = "https://learn.zone01kisumu.ke/api/content/root/public/subjects/ai/numpy/data/winequality-red.csv"

try:
    # Create a temporary file to store the downloaded data
    with tempfile.NamedTemporaryFile(delete=False, suffix='.csv') as temp_file:
        temp_filename = temp_file.name
    
    print("Downloading wine dataset...")
    urllib.request.urlretrieve(url, temp_filename)
    print("Download complete!")
    
    # Load the data using genfromtxt with delimiter ';', skip header, and optimize data types
    wine_data = np.genfromtxt(temp_filename, delimiter=';', skip_header=1, dtype=np.float32)
    
    # Clean up temporary file
    os.unlink(temp_filename)
    
except Exception as e:
    print(f"Error downloading or loading data: {e}")
    # If download fails, create mock data for demonstration
    print("Creating mock data for demonstration purposes...")
    np.random.seed(42)
    wine_data = np.random.rand(1599, 12).astype(np.float32)
    # Scale to realistic wine values
    wine_data[:, 0] = wine_data[:, 0] * 4 + 4      # fixed acidity: 4-8
    wine_data[:, 1] = wine_data[:, 1] * 0.5 + 0.2  # volatile acidity: 0.2-0.7
    wine_data[:, 8] = wine_data[:, 8] * 1 + 2.5    # pH: 2.5-3.5
    wine_data[:, 9] = wine_data[:, 9] * 0.8 + 0.3  # sulphates: 0.3-1.1
    wine_data[:, 10] = wine_data[:, 10] * 4 + 8    # alcohol: 8-12%
    wine_data[:, 11] = np.round(wine_data[:, 11] * 5 + 3)  # quality: 3-8

print("1. Data loaded and optimized:")
print(f"Shape: {wine_data.shape}")
print(f"Data type: {wine_data.dtype}")
print(f"Memory usage: {wine_data.nbytes} bytes")


# Step 2: Display specific rows (2nd, 7th, 12th)
# Note: genfromtxt skips header, so row indices are 0-based
rows_to_display = np.array([1, 6, 11])  # 2nd, 7th, 12th rows (0-indexed)
selected_rows = wine_data[rows_to_display]

print("2. Selected rows (2nd, 7th, 12th):")
print(selected_rows)
print(f"Shape of selected rows: {selected_rows.shape}\n")

# Step 3: Check if any wine has alcohol > 20%
alcohol_greater_than_20 = np.any(wine_data[:, 10] > 20.0)  # Alcohol is column 10 (0-indexed)
print("3. Any wine with alcohol > 20%:")
print(alcohol_greater_than_20)
print()

# Step 4: Calculate average alcohol percentage
average_alcohol = np.nanmean(wine_data[:, 10])
print("4. Average alcohol percentage:")
print(f"{average_alcohol:.2f}%")
print()

# Step 5: Statistical measures for pH values (column 8)
ph_values = wine_data[:, 8]  # pH is column 8

ph_stats = {
    'min': np.nanmin(ph_values),
    'max': np.nanmax(ph_values),
    '25th_percentile': np.nanpercentile(ph_values, 25),
    '50th_percentile': np.nanpercentile(ph_values, 50),
    '75th_percentile': np.nanpercentile(ph_values, 75),
    'mean': np.nanmean(ph_values)
}

print("5. pH statistics:")
for stat, value in ph_stats.items():
    print(f"{stat:15}: {value:.4f}")
print()

# Step 6: Average quality of wines with 20% least sulphate content
sulphates = wine_data[:, 9]  # Sulphates is column 9
quality = wine_data[:, 11]   # Quality is column 11

# Get 20th percentile of sulphates
sulphates_20th_percentile = np.nanpercentile(sulphates, 20)

# Create boolean mask for wines with sulphate <= 20th percentile
low_sulphate_mask = sulphates <= sulphates_20th_percentile

# Calculate average quality for these wines
avg_quality_low_sulphate = np.nanmean(quality[low_sulphate_mask])

print("6. Average quality of wines with 20% least sulphate:")
print(f"20th percentile of sulphates: {sulphates_20th_percentile:.4f}")
print(f"Average quality: {avg_quality_low_sulphate:.4f}")
print(f"Number of wines in this group: {np.sum(low_sulphate_mask)}")
print()

# Step 7: Mean of all variables for best and worst quality wines
best_quality = np.nanmax(quality)
worst_quality = np.nanmin(quality)

# Create masks for best and worst quality wines
best_quality_mask = quality == best_quality
worst_quality_mask = quality == worst_quality

# Calculate mean of all variables for each group
best_quality_means = np.nanmean(wine_data[best_quality_mask], axis=0)
worst_quality_means = np.nanmean(wine_data[worst_quality_mask], axis=0)

print("7. Mean of all variables for best and worst quality wines:")
print(f"Best quality: {best_quality}")
print(f"Worst quality: {worst_quality}")
print(f"Number of best quality wines: {np.sum(best_quality_mask)}")
print(f"Number of worst quality wines: {np.sum(worst_quality_mask)}")

# Column names for reference (from the dataset description)
column_names = [
    'fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
    'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
    'pH', 'sulphates', 'alcohol', 'quality'
]

print("\nMean values for best quality wines:")
for i, (name, value) in enumerate(zip(column_names, best_quality_means)):
    print(f"{name:20}: {value:.4f}")

print("\nMean values for worst quality wines:")
for i, (name, value) in enumerate(zip(column_names, worst_quality_means)):
    print(f"{name:20}: {value:.4f}")

# Exercise 8: Wine Dataset Analysis
## Fundamental data analysis using NumPy

Download complete!
1. Data loaded and optimized:
Shape: (1599, 12)
Data type: float32
Memory usage: 76752 bytes
2. Selected rows (2nd, 7th, 12th):
[[7.800e+00 8.800e-01 0.000e+00 2.600e+00 9.800e-02 2.500e+01 6.700e+01
  9.968e-01 3.200e+00 6.800e-01 9.800e+00 5.000e+00]
 [7.900e+00 6.000e-01 6.000e-02 1.600e+00 6.900e-02 1.500e+01 5.900e+01
  9.964e-01 3.300e+00 4.600e-01 9.400e+00 5.000e+00]
 [7.500e+00 5.000e-01 3.600e-01 6.100e+00 7.100e-02 1.700e+01 1.020e+02
  9.978e-01 3.350e+00 8.000e-01 1.050e+01 5.000e+00]]
Shape of selected rows: (3, 12)

3. Any wine with alcohol > 20%:
False

4. Average alcohol percentage:
10.42%

5. pH statistics:
min            : 2.7400
max            : 4.0100
25th_percentile: 3.2100
50th_percentile: 3.3100
75th_percentile: 3.4000
mean           : 3.3111

6. Average quality of wines with 20% least sulphate:
20th percentile of sulphates: 0.5400
Average quality: 5.2162
Number of w