In [2]:
# H1 TITLE
## H2 TITLE

In [1]:
print("Buy the dip ?")

Buy the dip ?


In [ ]:
# Exercise 1
## Numpy array (data types)

In [1]:
import numpy as np

my_array = np.array([
    10, #int
    3.142, #float
    "hello world", #string
    {"key":"value"}, #dictionary
    [1,2,3], #list
    (2,4,6), #tuple
    {4,8,12}, #set
    True, #boolean
    
], dtype=object) #the dtype=object is used to store heterogeneous types

for i in my_array:
    print(type(i))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'dict'>
<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'bool'>


In [ ]:
#Exercise 2
## numpy arrays with zeros

In [4]:
import numpy as np

#this creates a 1D array of dimention 300 with zeros(1,300)
zero_array = np.zeros(300)
# print(zero_array)

#reshape it to (3,100)
reshaped_array = zero_array.reshape(3,100)
print(reshaped_array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]]


In [ ]:
# Exercise 3: Slicing
## The goal of this exercise is to learn NumPy indexing/slicing. It allows to access values of the NumPy array efficiently and without a for loop.

In [9]:
import numpy as np

#an array of 100 int
arr_1_to_100 = np.arange(1,101)
# print(arr_1_to_100)

 #array for odd intergers
odd_array = arr_1_to_100[::2] #or arr_1_to_100[arr_1_to_100 % 2 == 1]
# print(odd_array)

#array with even interger reversed
even_array = arr_1_to_100[1::2][::-1]
# print(even_array)

#array with each third element from 2nd set to 0
modified_array = arr_1_to_100.copy() #not to change the original
modified_array[1::3] = 0
print(modified_array)


[  1   0   3   4   0   6   7   0   9  10   0  12  13   0  15  16   0  18
  19   0  21  22   0  24  25   0  27  28   0  30  31   0  33  34   0  36
  37   0  39  40   0  42  43   0  45  46   0  48  49   0  51  52   0  54
  55   0  57  58   0  60  61   0  63  64   0  66  67   0  69  70   0  72
  73   0  75  76   0  78  79   0  81  82   0  84  85   0  87  88   0  90
  91   0  93  94   0  96  97   0  99 100]


In [ ]:
# Exercise 4: Random generator
## Generating random data with normal and uniform distributions

In [28]:
import numpy as np

np.random.seed(888) #makes the random numbers reproducible

normal_1d = np.random.randn(100)

# print(f"shape: {normal_1d.shape}")
# print(f"sample: {normal_1d[:4]}...\n")

#8x8 uniform integer array (1-10) aka 2d
uniform_2d = np.random.randint(1,11,size=(8,8))
# print(f" shape: {uniform_2d.shape}\n")
# print(uniform_2d)

#4x2x5 uniform integer array (1-17)

uniform_3d = np.random.randint(1,18,size=(4,2,5))
print(f"shape: {uniform_3d.shape}")
print(uniform_3d)

shape: (4, 2, 5)
[[[ 5  2 13 16 15]
  [ 5  5  2 11  3]]

 [[ 8 13  6  4 17]
  [ 2  8  1 13 10]]

 [[12 17 17 12  1]
  [10  8 17  5 11]]

 [[ 9 14  2 15 13]
  [12 14  6 14  2]]]
